In [ ]:
import requests
import pandas as pd

base_folder_link = "https://github.com/Laxeros07/Question-Answering-about-Geometries/blob/main/Model_Testing/"

gemma_4_31_link = base_folder_link+"test_results_gemma-4-31b-it.xlsx"
glm_4_7_link = base_folder_link+"test_results_glm-4.7.xlsx"
gpt_4o_mini_link = base_folder_link+"test_results_gpt-4o-mini.xlsx"
gpt_5_4_mini_link = base_folder_link+"test_results_gpt-5.4-mini.xlsx"
gpt_5_4_nano_link = base_folder_link+"test_results_gpt-5.4-nano.xlsx"
qwen_3_5_122b_a10b_link = base_folder_link+"test_results_qwen3.5-122b-a10b.xlsx"


def read_excel_from_url(url):

  # Convert the 'blob' URL to a 'raw' URL for direct file access
  raw_url = url.replace('github.com', 'raw.githubusercontent.com').replace('/blob/', '/')

  df = pd.DataFrame()

  print(f"Reading Excel from: {raw_url}")

  try:
      # Read the Excel file directly into a pandas DataFrame
      df = pd.read_excel(raw_url)
  except Exception as e:
      print(f"Error reading Excel file: {e}")

  return df

In [ ]:
df_gemma_4_31 = read_excel_from_url(gemma_4_31_link)
df_glm_4_7 = read_excel_from_url(glm_4_7_link)
df_gpt_4o_mini = read_excel_from_url(gpt_4o_mini_link)
df_gpt_5_4_mini = read_excel_from_url(gpt_5_4_mini_link)
df_gpt_5_4_nano = read_excel_from_url(gpt_5_4_nano_link)
df_qwen_3_5_122b_a10b = read_excel_from_url(qwen_3_5_122b_a10b_link)

Reading Excel from: https://raw.githubusercontent.com/Laxeros07/Question-Answering-about-Geometries/main/Model_Testing/test_results_gemma-4-31b-it.xlsx
Reading Excel from: https://raw.githubusercontent.com/Laxeros07/Question-Answering-about-Geometries/main/Model_Testing/test_results_glm-4.7.xlsx
Reading Excel from: https://raw.githubusercontent.com/Laxeros07/Question-Answering-about-Geometries/main/Model_Testing/test_results_gpt-4o-mini.xlsx
Reading Excel from: https://raw.githubusercontent.com/Laxeros07/Question-Answering-about-Geometries/main/Model_Testing/test_results_gpt-5.4-mini.xlsx
Reading Excel from: https://raw.githubusercontent.com/Laxeros07/Question-Answering-about-Geometries/main/Model_Testing/test_results_gpt-5.4-nano.xlsx
Reading Excel from: https://raw.githubusercontent.com/Laxeros07/Question-Answering-about-Geometries/main/Model_Testing/test_results_qwen3.5-122b-a10b.xlsx

In [ ]:
# Combine all the loaded DataFrames into a single DataFrame
all_dfs = {
    'gemma_4_31': df_gemma_4_31,
    'glm_4_7': df_glm_4_7,
    'gpt_4o_mini': df_gpt_4o_mini,
    'gpt_5_4_mini': df_gpt_5_4_mini,
    'gpt_5_4_nano': df_gpt_5_4_nano,
    'qwen_3_5_122b_a10b': df_qwen_3_5_122b_a10b
}

# Add a 'Model' column to each DataFrame before concatenating
combined_df = pd.concat([df.assign(Model=name) for name, df in all_dfs.items()], ignore_index=True)
display(combined_df.head())

,Language,Query_Type,Question,Expected_Answer,Actual_Answer,Runtime (s),Score,Status,Reason,BERT_P,BERT_R,BERT_F1,Model
0,E,object/footprint,Where is the city of Münster located?,The city of Münster is not unique and refers t...,The entity Münster refers to more than one pla...,10.146,1.0,PASSED,The actual answer includes both Münster locati...,0.7973,0.8055,0.8017,gemma_4_31
1,E,object/footprint,Where is the city of Cologne located?,The city of Cologne is located in the administ...,The city of Köln is located in the district of...,5.472,1.0,PASSED,The actual answer includes the expected detail...,0.7347,0.8177,0.7759,gemma_4_31
2,E,object/footprint,Where is the administrative community of Eisen...,The administrative community of Eisenhüttensta...,The administrative community of Eisenhüttensta...,5.525,1.0,PASSED,The ACTUAL answer includes all information fro...,0.9081,0.9683,0.9380,gemma_4_31
3,E,object/footprint,Where is the administrative community of Esens...,The administrative community of Esens is locat...,The administrative community of Esens is locat...,5.435,1.0,PASSED,The actual answer states that Esens is in the ...,0.5987,0.7871,0.6897,gemma_4_31
4,E,object/footprint,Where is the district of Gießen located?,The district of Gießen is located in the feder...,The district of Gießen is located in the Feder...,5.187,1.0,PASSED,The actual answer states that the district of ...,0.7450,0.8816,0.8118,gemma_4_31

# All data together

In [ ]:
# Filter out rows where 'Language' is 'AVERAGE' or NaN, as these are summary rows
# And ensure 'Score' is numeric for statistics
data_for_stats = combined_df[combined_df['Language'].notna() & (combined_df['Language'] != 'AVERAGE')].copy()
data_for_stats['Score'] = pd.to_numeric(data_for_stats['Score'], errors='coerce')

# Group by 'Language' and calculate descriptive statistics for numerical columns
descriptive_stats_by_language = data_for_stats.groupby('Language')[['Runtime (s)', 'Score', 'BERT_P', 'BERT_R', 'BERT_F1']].describe()

print("\nDescriptive Statistics per Language:")
display(descriptive_stats_by_language)

Descriptive Statistics per Language:

         Runtime (s)                                                         \
               count       mean        std    min     25%     50%       75%
Language
DE             240.0  24.238212  31.324549  3.625  5.0095  6.8915  33.13100
E              240.0  30.540375  59.613335  3.752  4.8930  6.3720  36.29875
FR             240.0  25.119575  35.679472  3.627  4.8050  6.4935  33.15125

                   Score            ...    BERT_R         BERT_F1            \
              max  count      mean  ...       75%     max   count      mean
Language                            ...
DE        135.266  240.0  0.708125  ...  0.761000  1.0000   240.0  0.474125
E         616.002  240.0  0.756913  ...  0.785925  1.0000   240.0  0.505101
FR        176.677  240.0  0.614708  ...  0.717050  0.9123   240.0  0.399873


               std     min       25%      50%      75%     max
Language
DE        0.282171 -0.1806  0.289425  0.53165  0.68980  1.0000
E         0.251234 -0.0356  0.350825  0.56320  0.69335  1.0000
FR        0.273635 -0.3560  0.184675  0.44315  0.62270  0.8863

[3 rows x 40 columns]

# One Data Frame at once

In [ ]:
# calculate all descriptive stats for a dataframe
def calculate_descriptive_stats(df):
  df_stats = df[df['Language'].notna() & (df['Language'] != 'AVERAGE')].copy()
  df_stats['Score'] = pd.to_numeric(df_stats['Score'], errors='coerce')
  descriptive_stats_by_language_nv = df_stats.groupby('Language')[['Runtime (s)', 'Score', 'Status', 'BERT_P', 'BERT_R', 'BERT_F1']].describe()
  descriptive_stats_by_language_cv = df_stats.groupby('Language')['Status'].describe(include='object')
  return descriptive_stats_by_language_nv, descriptive_stats_by_language_cv


def show_stats_by_language(all_dfs, current_df_key):

  descriptive_stats_by_language_nv, descriptive_stats_by_language_cv = calculate_descriptive_stats(all_dfs[current_df_key])

  # Define the numerical columns for which you want descriptive statistics
  selected_numeric_columns = ['Runtime (s)', 'Score', 'BERT_F1']

  # Define the descriptive statistics you want to include
  selected_stats = ['count', 'mean', 'std', 'min', 'max']

  # Select only the desired statistics for the specified columns
  desired_stats = descriptive_stats_by_language_nv.loc[:, (selected_numeric_columns, selected_stats)]

  print(f"\nDescriptive Statistics per Language (Custom Columns and Selection) for {current_df_key} (Numerical Variables Only):")
  display(desired_stats)

  print(f"\nDescriptive Statistics per Language (Custom Columns and Selection) for {current_df_key} (Categorical Variables Only):")
  display(descriptive_stats_by_language_cv)

In [ ]:
current_df_key = 'gpt_5_4_mini' # Explicitly define the key for the current DataFrame

calculate_descriptive_stats(all_dfs[current_df_key])

show_stats_by_language(all_dfs, current_df_key)

Descriptive Statistics per Language (Custom Columns and Selection) for gpt_5_4_mini (Numerical Variables Only):

         Runtime (s)                                    Score           \
               count     mean        std    min     max count     mean
Language
DE              40.0  9.86295  11.325618  3.767  39.523  40.0  0.78325
E               40.0  9.91935  11.891340  3.837  48.075  40.0  0.80550
FR              40.0  9.41540  11.438788  3.687  43.484  40.0  0.60675

                             BERT_F1
               std  min  max   count      mean       std     min     max
Language
DE        0.403436  0.0  1.0    40.0  0.492065  0.269907 -0.1806  0.9014
E         0.380121  0.0  1.0    40.0  0.535173  0.221435 -0.0298  0.8784
FR        0.468469  0.0  1.0    40.0  0.354255  0.312624 -0.3560  0.7486

Descriptive Statistics per Language (Custom Columns and Selection) for gpt_5_4_mini (Categorical Variables Only):

         count unique     top freq
Language
DE          40      2  PASSED   30
E           40      2  PASSED   31
FR          40      2  PASSED   22

In [ ]:
df_gemma_4_31.keys(), print(pd.unique(df_gemma_4_31["Status"]))

['PASSED' 'FAILED' 'ERROR' nan]

(Index(['Language', 'Query_Type', 'Question', 'Expected_Answer',
        'Actual_Answer', 'Runtime (s)', 'Score', 'Status', 'Reason', 'BERT_P',
        'BERT_R', 'BERT_F1'],
       dtype='object'),
 None)

In [ ]:
for key in all_dfs.keys():
  show_stats_by_language(all_dfs, key)

Descriptive Statistics per Language (Custom Columns and Selection) for gemma_4_31 (Numerical Variables Only):

         Runtime (s)                                        Score           \
               count       mean         std    min      max count     mean
Language
DE              40.0  13.360450   13.097039  5.133   55.953  40.0  0.79225
E               40.0  51.253125  123.448969  5.187  616.002  40.0  0.78100
FR              40.0  12.483500   10.570598  5.954   43.441  40.0  0.74900

                             BERT_F1
               std  min  max   count      mean       std     min     max
Language
DE        0.395251  0.0  1.0    40.0  0.597455  0.292714 -0.0469  1.0000
E         0.398432  0.0  1.0    40.0  0.641600  0.260996  0.0153  1.0000
FR        0.411051  0.0  1.0    40.0  0.530430  0.280425 -0.0657  0.8863

Descriptive Statistics per Language (Custom Columns and Selection) for gemma_4_31 (Categorical Variables Only):

         count unique     top freq
Language
DE          40      2  PASSED   30
E           40      2  PASSED   30
FR          40      3  PASSED   27

Descriptive Statistics per Language (Custom Columns and Selection) for glm_4_7 (Numerical Variables Only):

         Runtime (s)                                      Score           \
               count       mean        std    min     max count     mean
Language
DE              40.0  15.685500  13.037141  4.009  43.169  40.0  0.70000
E               40.0  13.037775  12.595402  4.157  43.818  40.0  0.79425
FR              40.0  13.768350  12.295496  4.393  43.043  40.0  0.63250

                             BERT_F1
               std  min  max   count      mean       std     min     max
Language
DE        0.450641  0.0  1.0    40.0  0.485532  0.293270 -0.1107  0.8610
E         0.393393  0.0  1.0    40.0  0.519887  0.252246 -0.0356  0.9113
FR        0.474281  0.0  1.0    40.0  0.462510  0.311235 -0.1852  0.8250

Descriptive Statistics per Language (Custom Columns and Selection) for glm_4_7 (Categorical Variables Only):

         count unique     top freq
Language
DE          40      3  PASSED   27
E           40      3  PASSED   31
FR          40      3  PASSED   23

Descriptive Statistics per Language (Custom Columns and Selection) for gpt_4o_mini (Numerical Variables Only):

         Runtime (s)                                      Score            \
               count       mean        std    min     max count      mean
Language
DE              40.0   8.890750   8.963232  3.625  38.991  40.0  0.492500
E               40.0  10.585625  11.691728  3.752  42.002  40.0  0.626125
FR              40.0   8.772150  10.267412  3.627  41.584  40.0  0.380500

                             BERT_F1
               std  min  max   count      mean       std     min     max
Language
DE        0.488529  0.0  1.0    40.0  0.304927  0.235330 -0.0959  0.9014
E         0.456076  0.0  1.0    40.0  0.341595  0.195633 -0.0118  0.6501
FR        0.477928  0.0  1.0    40.0  0.257727  0.202434 -0.1188  0.6892

Descriptive Statistics per Language (Custom Columns and Selection) for gpt_4o_mini (Categorical Variables Only):

         count unique     top freq
Language
DE          40      3  FAILED   21
E           40      3  PASSED   22
FR          40      3  FAILED   25

Descriptive Statistics per Language (Custom Columns and Selection) for gpt_5_4_mini (Numerical Variables Only):

         Runtime (s)                                    Score           \
               count     mean        std    min     max count     mean
Language
DE              40.0  9.86295  11.325618  3.767  39.523  40.0  0.78325
E               40.0  9.91935  11.891340  3.837  48.075  40.0  0.80550
FR              40.0  9.41540  11.438788  3.687  43.484  40.0  0.60675

                             BERT_F1
               std  min  max   count      mean       std     min     max
Language
DE        0.403436  0.0  1.0    40.0  0.492065  0.269907 -0.1806  0.9014
E         0.380121  0.0  1.0    40.0  0.535173  0.221435 -0.0298  0.8784
FR        0.468469  0.0  1.0    40.0  0.354255  0.312624 -0.3560  0.7486

Descriptive Statistics per Language (Custom Columns and Selection) for gpt_5_4_mini (Categorical Variables Only):

         count unique     top freq
Language
DE          40      2  PASSED   30
E           40      2  PASSED   31
FR          40      2  PASSED   22

Descriptive Statistics per Language (Custom Columns and Selection) for gpt_5_4_nano (Numerical Variables Only):

         Runtime (s)                                      Score            \
               count       mean        std    min     max count      mean
Language
DE              40.0  11.442650  11.497593  4.342  43.613  40.0  0.747500
E               40.0  11.120175  11.687957  4.497  45.878  40.0  0.769102
FR              40.0   9.124550  10.808355  4.153  49.051  40.0  0.550000

                             BERT_F1
               std  min  max   count      mean       std     min     max
Language
DE        0.424105  0.0  1.0    40.0  0.437383  0.222344 -0.1233  0.8231
E         0.397419  0.0  1.0    40.0  0.436395  0.211868 -0.0262  0.8664
FR        0.486616  0.0  1.0    40.0  0.312090  0.185838 -0.0397  0.5964

Descriptive Statistics per Language (Custom Columns and Selection) for gpt_5_4_nano (Categorical Variables Only):

         count unique     top freq
Language
DE          40      2  PASSED   29
E           40      2  PASSED   28
FR          40      2  PASSED   21

Descriptive Statistics per Language (Custom Columns and Selection) for qwen_3_5_122b_a10b (Numerical Variables Only):

         Runtime (s)                                        Score           \
               count       mean        std     min      max count     mean
Language
DE              40.0  86.186975  24.020179  30.515  135.266  40.0  0.73325
E               40.0  87.326200  25.927457  38.210  145.362  40.0  0.76550
FR              40.0  97.153500  27.893804  42.584  176.677  40.0  0.76950

                             BERT_F1
               std  min  max   count      mean       std     min     max
Language
DE        0.428135  0.0  1.0    40.0  0.527390  0.298082 -0.0531  0.9336
E         0.408869  0.0  1.0    40.0  0.555955  0.260165 -0.0118  1.0000
FR        0.393674  0.0  1.0    40.0  0.482222  0.225563 -0.1734  0.7443

Descriptive Statistics per Language (Custom Columns and Selection) for qwen_3_5_122b_a10b (Categorical Variables Only):

         count unique     top freq
Language
DE          40      2  PASSED   27
E           40      2  PASSED   29
FR          40      2  PASSED   28

# Computing Multi-Lingual Consistency

In [ ]:
df_gemma_4_31

,Language,Query_Type,Question,Expected_Answer,Actual_Answer,Runtime (s),Score,Status,Reason,BERT_P,BERT_R,BERT_F1
0,E,object/footprint,Where is the city of Münster located?,The city of Münster is not unique and refers t...,The entity Münster refers to more than one pla...,10.146,1.0000,PASSED,The actual answer includes both Münster locati...,0.7973,0.8055,0.8017
1,E,object/footprint,Where is the city of Cologne located?,The city of Cologne is located in the administ...,The city of Köln is located in the district of...,5.472,1.0000,PASSED,The actual answer includes the expected detail...,0.7347,0.8177,0.7759
2,E,object/footprint,Where is the administrative community of Eisen...,The administrative community of Eisenhüttensta...,The administrative community of Eisenhüttensta...,5.525,1.0000,PASSED,The ACTUAL answer includes all information fro...,0.9081,0.9683,0.9380
3,E,object/footprint,Where is the administrative community of Esens...,The administrative community of Esens is locat...,The administrative community of Esens is locat...,5.435,1.0000,PASSED,The actual answer states that Esens is in the ...,0.5987,0.7871,0.6897
4,E,object/footprint,Where is the district of Gießen located?,The district of Gießen is located in the feder...,The district of Gießen is located in the Feder...,5.187,1.0000,PASSED,The actual answer states that the district of ...,0.7450,0.8816,0.8118
...,...,...,...,...,...,...,...,...,...,...,...,...
116,FR,cardinal (1:N),Quelles sont les communautés administratives s...,Les communes administratives situées au nord d...,Les communautés administratives situées au nor...,33.822,0.6000,FAILED,"L’ACTUAL inclut Altenholz, Dänischenhagen, Kap...",0.7203,0.8056,0.7625
117,FR,distance (1:N),Quels sont les districts situés dans un rayon ...,Le district de Göttingen comprend les district...,Les districts situés dans un rayon de 10 km au...,43.441,1.0000,PASSED,L’ACTUAL liste bien tous les districts attendu...,0.6891,0.7561,0.7226
118,FR,distance (1:N),Quelles sont les villes situées dans un rayon ...,Les villes suivantes sont situées dans un rayo...,Les villes situées dans un rayon de 5 km autou...,40.798,1.0000,PASSED,L’ACTUAL liste exactement toutes les villes at...,0.7608,0.7357,0.7486
119,FR,distance (1:N),Quelles sont les villes situées dans un rayon ...,Les villes situées à moins de 2 km de Munich s...,ERROR: 500 Server Error: Internal Server Error...,24.778,0.0000,ERROR,500 Server Error: Internal Server Error for ur...,0.0000,0.0000,0.0000
120,NaN,NaN,AVERAGE,NaN,NaN,25.699,0.7806,NaN,NaN,0.5741,0.6254,0.5948

In [ ]:
import pandas as pd

# perform a row-wise comparison: give a 1 if both rows are the same (PASSED, FAILED, ERROR), 0 if not
def compute_multi_lingual_consistency(all_dfs, model_name):

  col_names =  ['model', 'EN-DE', 'EN-DE Results', 'EN-FR', 'EN-FR Results', 'DE-FR', 'DE-FR Results']

  current_df = all_dfs[model_name]

  mlc_df  = pd.DataFrame(columns = col_names)

  offset_en_de = 40
  offset_en_fr = 80

  for i in range(40):

    en_row_status = current_df.loc[i, 'Status']
    de_row_status = current_df.loc[i + offset_en_de, 'Status']
    fr_row_status = current_df.loc[i + offset_en_fr, 'Status']

    mlc_df.loc[i, 'model'] = model_name
    mlc_df.loc[i, 'Query_Type'] = current_df.loc[i, 'Query_Type']
    mlc_df.loc[i, 'EN-DE'] = int(en_row_status == de_row_status)
    mlc_df.loc[i, 'EN-FR'] = int(en_row_status == fr_row_status)
    mlc_df.loc[i, 'DE-FR'] = int(de_row_status == fr_row_status)

    mlc_df.loc[i, 'EN-DE Results'] = en_row_status+"/"+de_row_status
    mlc_df.loc[i, 'EN-FR Results'] = en_row_status+"/"+fr_row_status
    mlc_df.loc[i, 'DE-FR Results'] = de_row_status+"/"+fr_row_status

  return mlc_df

In [ ]:
mlc_df = compute_multi_lingual_consistency(all_dfs, 'gemma_4_31')
mlc_df.describe()

,model,EN-DE,EN-DE Results,EN-FR,EN-FR Results,DE-FR,DE-FR Results,Query_Type
count,40,40,40,40,40,40,40,40
unique,1,2,4,2,5,2,4,9
top,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,object/footprint
freq,40,36,28,32,25,36,27,10

In [ ]:
mlc_df

,model,EN-DE,EN-DE Results,EN-FR,EN-FR Results,DE-FR,DE-FR Results,Query_Type
0,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,object/footprint
1,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,object/footprint
2,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,object/footprint
3,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,object/footprint
4,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,object/footprint
5,gemma_4_31,1,PASSED/PASSED,0,PASSED/FAILED,0,PASSED/FAILED,object/footprint
6,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,object/footprint
7,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,object/footprint
8,gemma_4_31,1,FAILED/FAILED,1,FAILED/FAILED,1,FAILED/FAILED,object/footprint
9,gemma_4_31,1,FAILED/FAILED,1,FAILED/FAILED,1,FAILED/FAILED,object/footprint
10,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,physical/parts - enumeration
11,gemma_4_31,1,PASSED/PASSED,0,PASSED/FAILED,0,PASSED/FAILED,physical/parts - enumeration
12,gemma_4_31,1,PASSED/PASSED,0,PASSED/FAILED,0,PASSED/FAILED,physical/parts - enumeration
13,gemma_4_31,0,PASSED/FAILED,0,PASSED/FAILED,1,FAILED/FAILED,physical/parts - enumeration
14,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,physical/parts - enumeration
15,gemma_4_31,1,FAILED/FAILED,1,FAILED/FAILED,1,FAILED/FAILED,physical/parts - comparison
16,gemma_4_31,1,FAILED/FAILED,1,FAILED/FAILED,1,FAILED/FAILED,physical/parts - comparison
17,gemma_4_31,1,FAILED/FAILED,1,FAILED/FAILED,1,FAILED/FAILED,physical/parts - comparison
18,gemma_4_31,1,FAILED/FAILED,1,FAILED/FAILED,1,FAILED/FAILED,physical/parts - comparison
19,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,physical/parts - comparison
20,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,topological (1:1)
21,gemma_4_31,0,FAILED/PASSED,0,FAILED/PASSED,1,PASSED/PASSED,topological (1:1)
22,gemma_4_31,0,FAILED/PASSED,0,FAILED/PASSED,1,PASSED/PASSED,topological (1:1)
23,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,topological (1:1)
24,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,cardinal (1:1)
25,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,cardinal (1:1)
26,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,cardinal (1:1)
27,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,distance (1:1)
28,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,distance (1:1)
29,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,distance (1:1)
30,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,topological (1:N)
31,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,topological (1:N)
32,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,topological (1:N)
33,gemma_4_31,0,PASSED/FAILED,0,PASSED/FAILED,1,FAILED/FAILED,topological (1:N)
34,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,cardinal (1:N)
35,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,cardinal (1:N)
36,gemma_4_31,1,FAILED/FAILED,1,FAILED/FAILED,1,FAILED/FAILED,cardinal (1:N)
37,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,distance (1:N)
38,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,distance (1:N)
39,gemma_4_31,1,FAILED/FAILED,0,FAILED/ERROR,0,FAILED/ERROR,distance (1:N)

In [ ]:
mlc_df.describe().keys()

Index(['model', 'EN-DE', 'EN-DE Results', 'EN-FR', 'EN-FR Results', 'DE-FR',
       'DE-FR Results', 'Query_Type'],
      dtype='object')

In [ ]:
for key in all_dfs.keys():
  mlc_df = compute_multi_lingual_consistency(all_dfs, key)
  print(f"\n Multilingual consistency for model {key} \n")
  display(mlc_df.describe())

 Multilingual consistency for model gemma_4_31

,model,EN-DE,EN-DE Results,EN-FR,EN-FR Results,DE-FR,DE-FR Results,Query_Type
count,40,40,40,40,40,40,40,40
unique,1,2,4,2,5,2,4,9
top,gemma_4_31,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,object/footprint
freq,40,36,28,32,25,36,27,10

 Multilingual consistency for model glm_4_7

,model,EN-DE,EN-DE Results,EN-FR,EN-FR Results,DE-FR,DE-FR Results,Query_Type
count,40,40,40,40,40,40,40,40
unique,1,2,6,2,7,2,7,9
top,glm_4_7,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,object/footprint
freq,40,34,26,29,22,27,19,10

 Multilingual consistency for model gpt_4o_mini

,model,EN-DE,EN-DE Results,EN-FR,EN-FR Results,DE-FR,DE-FR Results,Query_Type
count,40,40,40,40,40,40,40,40
unique,1,2,8,2,7,2,6,9
top,gpt_4o_mini,1,PASSED/PASSED,1,FAILED/FAILED,0,FAILED/FAILED,object/footprint
freq,40,26,13,23,12,21,13,10

 Multilingual consistency for model gpt_5_4_mini

,model,EN-DE,EN-DE Results,EN-FR,EN-FR Results,DE-FR,DE-FR Results,Query_Type
count,40,40,40,40,40,40,40,40
unique,1,2,4,2,4,2,4,9
top,gpt_5_4_mini,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,object/footprint
freq,40,35,28,25,19,24,18,10

 Multilingual consistency for model gpt_5_4_nano

,model,EN-DE,EN-DE Results,EN-FR,EN-FR Results,DE-FR,DE-FR Results,Query_Type
count,40,40,40,40,40,40,40,40
unique,1,2,4,2,4,2,4,9
top,gpt_5_4_nano,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,object/footprint
freq,40,33,25,23,16,24,17,10

 Multilingual consistency for model qwen_3_5_122b_a10b

,model,EN-DE,EN-DE Results,EN-FR,EN-FR Results,DE-FR,DE-FR Results,Query_Type
count,40,40,40,40,40,40,40,40
unique,1,2,4,2,4,2,4,9
top,qwen_3_5_122b_a10b,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,object/footprint
freq,40,34,25,33,25,31,23,10

In [ ]:
df_gemma_4_31

,Language,Query_Type,Question,Expected_Answer,Actual_Answer,Runtime (s),Score,Status,Reason,BERT_P,BERT_R,BERT_F1
0,E,object/footprint,Where is the city of Münster located?,The city of Münster is not unique and refers t...,The entity Münster refers to more than one pla...,10.146,1.0000,PASSED,The actual answer includes both Münster locati...,0.7973,0.8055,0.8017
1,E,object/footprint,Where is the city of Cologne located?,The city of Cologne is located in the administ...,The city of Köln is located in the district of...,5.472,1.0000,PASSED,The actual answer includes the expected detail...,0.7347,0.8177,0.7759
2,E,object/footprint,Where is the administrative community of Eisen...,The administrative community of Eisenhüttensta...,The administrative community of Eisenhüttensta...,5.525,1.0000,PASSED,The ACTUAL answer includes all information fro...,0.9081,0.9683,0.9380
3,E,object/footprint,Where is the administrative community of Esens...,The administrative community of Esens is locat...,The administrative community of Esens is locat...,5.435,1.0000,PASSED,The actual answer states that Esens is in the ...,0.5987,0.7871,0.6897
4,E,object/footprint,Where is the district of Gießen located?,The district of Gießen is located in the feder...,The district of Gießen is located in the Feder...,5.187,1.0000,PASSED,The actual answer states that the district of ...,0.7450,0.8816,0.8118
...,...,...,...,...,...,...,...,...,...,...,...,...
116,FR,cardinal (1:N),Quelles sont les communautés administratives s...,Les communes administratives situées au nord d...,Les communautés administratives situées au nor...,33.822,0.6000,FAILED,"L’ACTUAL inclut Altenholz, Dänischenhagen, Kap...",0.7203,0.8056,0.7625
117,FR,distance (1:N),Quels sont les districts situés dans un rayon ...,Le district de Göttingen comprend les district...,Les districts situés dans un rayon de 10 km au...,43.441,1.0000,PASSED,L’ACTUAL liste bien tous les districts attendu...,0.6891,0.7561,0.7226
118,FR,distance (1:N),Quelles sont les villes situées dans un rayon ...,Les villes suivantes sont situées dans un rayo...,Les villes situées dans un rayon de 5 km autou...,40.798,1.0000,PASSED,L’ACTUAL liste exactement toutes les villes at...,0.7608,0.7357,0.7486
119,FR,distance (1:N),Quelles sont les villes situées dans un rayon ...,Les villes situées à moins de 2 km de Munich s...,ERROR: 500 Server Error: Internal Server Error...,24.778,0.0000,ERROR,500 Server Error: Internal Server Error for ur...,0.0000,0.0000,0.0000
120,NaN,NaN,AVERAGE,NaN,NaN,25.699,0.7806,NaN,NaN,0.5741,0.6254,0.5948

In [ ]:
df_gemma_4_31.keys()

Index(['Language', 'Query_Type', 'Question', 'Expected_Answer',
       'Actual_Answer', 'Runtime (s)', 'Score', 'Status', 'Reason', 'BERT_P',
       'BERT_R', 'BERT_F1'],
      dtype='object')

# Fine-Grained Stats

In [ ]:
print(all_dfs.keys())

MODEL_NAME = "gpt_5_4_mini"

dict_keys(['gemma_4_31', 'glm_4_7', 'gpt_4o_mini', 'gpt_5_4_mini', 'gpt_5_4_nano', 'qwen_3_5_122b_a10b'])

## Stats per language and per query

In [ ]:
# calculate all descriptive stats for a dataframe
def create_table_per_language(all_dfs, model_name):

  df = all_dfs[model_name]

  df_stats = df[df['Language'].notna() & (df['Language'] != 'AVERAGE')].copy()
  df_stats['Score'] = pd.to_numeric(df_stats['Score'], errors='coerce')

  df_stats_en = df_stats[df_stats['Language'] == 'E'].copy()
  df_stats_de = df_stats[df_stats['Language'] == 'DE'].copy()
  df_stats_fr = df_stats[df_stats['Language'] == 'FR'].copy()

  df_stats_en_nv = df_stats.groupby('Query_Type')[['Runtime (s)', 'Score', 'Status', 'BERT_P', 'BERT_R', 'BERT_F1']].describe()
  df_stats_en_cv = df_stats.groupby('Query_Type')['Status'].describe(include='object')
  return df_stats_en, df_stats_de, df_stats_fr, model_name


def calculate_descriptive_stats_per_query(df, model_name):

  ## NUMERICAL VARIABLES
  df_stats_nv = df.groupby('Query_Type')[['Runtime (s)', 'Score', 'Status', 'BERT_P', 'BERT_R', 'BERT_F1']].describe()

  # Define the numerical columns for which you want descriptive statistics
  selected_numeric_columns = ['Runtime (s)', 'Score', 'BERT_F1']

  # Define the descriptive statistics you want to include
  selected_stats = ['count', 'mean', 'std', 'min', 'max']

  # Select only the desired statistics for the specified columns
  desired_stats_nv = df_stats_nv.loc[:, (selected_numeric_columns, selected_stats)]

  ## CATEGORICAL VARIABLES = STATUS
  status_counts = df.groupby(['Query_Type', 'Status']).size().unstack(fill_value=0)

  # Calculate the total count for each Query_Type
  status_counts['Total'] = status_counts.sum(axis=1)

  # Calculate the percentage of 'PASSED' for each Query_Type
  status_counts['Percentage_PASSED'] = (status_counts['PASSED'] / status_counts['Total']) * 100

  return desired_stats_nv, status_counts, model_name




df_en, df_de, df_fr, model_name = create_table_per_language(all_dfs, MODEL_NAME)

desired_stats_nv_en, status_counts_en, model_name = calculate_descriptive_stats_per_query(df_en, model_name)
desired_stats_nv_de, status_counts_de, model_name = calculate_descriptive_stats_per_query(df_de, model_name)
desired_stats_nv_fr, status_counts_fr, model_name = calculate_descriptive_stats_per_query(df_fr, model_name)

display(desired_stats_nv_en)
display(status_counts_en)

                             Runtime (s)                                       \
                                   count       mean       std     min     max
Query_Type
cardinal (1:1)                       3.0   5.301667  0.520919   4.969   5.902
cardinal (1:N)                       3.0  31.089333  0.361428  30.793  31.492
distance (1:1)                       3.0  10.529000  1.082050   9.453  11.617
distance (1:N)                       3.0  42.679333  5.234256  37.623  48.075
object/footprint                    10.0   4.847900  1.524859   3.931   9.044
physical/parts - comparison          5.0   4.361400  0.322552   4.040   4.748
physical/parts - enumeration         5.0   4.295400  0.172994   4.100   4.539
topological (1:1)                    4.0   5.041000  0.685403   4.545   6.052
topological (1:N)                    4.0   4.012250  0.216923   3.837   4.329

                             Score                                BERT_F1  \
                             count      mean       std   min  max   count
Query_Type
cardinal (1:1)                 3.0  1.000000  0.000000  1.00  1.0     3.0
cardinal (1:N)                 3.0  1.000000  0.000000  1.00  1.0     3.0
distance (1:1)                 3.0  1.000000  0.000000  1.00  1.0     3.0
distance (1:N)                 3.0  0.906667  0.161658  0.72  1.0     3.0
object/footprint              10.0  0.660000  0.459952  0.00  1.0    10.0
physical/parts - comparison    5.0  0.400000  0.547723  0.00  1.0     5.0
physical/parts - enumeration   5.0  1.000000  0.000000  1.00  1.0     5.0
topological (1:1)              4.0  0.725000  0.485627  0.00  1.0     4.0
topological (1:N)              4.0  1.000000  0.000000  1.00  1.0     4.0


                                  mean       std     min     max
Query_Type
cardinal (1:1)                0.529200  0.325024  0.2355  0.8784
cardinal (1:N)                0.506267  0.101930  0.4058  0.6096
distance (1:1)                0.519167  0.178781  0.3162  0.6533
distance (1:N)                0.663367  0.095763  0.5929  0.7724
object/footprint              0.490210  0.300846 -0.0298  0.8777
physical/parts - comparison   0.553580  0.108563  0.4525  0.6986
physical/parts - enumeration  0.697480  0.049676  0.6286  0.7386
topological (1:1)             0.253800  0.206334 -0.0118  0.4921
topological (1:N)             0.645075  0.095494  0.5653  0.7725

Status                        FAILED  PASSED  Total  Percentage_PASSED
Query_Type
cardinal (1:1)                     0       3      3         100.000000
cardinal (1:N)                     0       3      3         100.000000
distance (1:1)                     0       3      3         100.000000
distance (1:N)                     1       2      3          66.666667
object/footprint                   4       6     10          60.000000
physical/parts - comparison        3       2      5          40.000000
physical/parts - enumeration       0       5      5         100.000000
topological (1:1)                  1       3      4          75.000000
topological (1:N)                  0       4      4         100.000000

In [ ]:
from numpy import average
status_counts_en.keys(), status_counts_en.Percentage_PASSED
average(status_counts_en.Percentage_PASSED)

np.float64(82.4074074074074)

## Multilingual consistency

In [ ]:
import pandas as pd

# perform a row-wise comparison: give a 1 if both rows are the same (PASSED, FAILED, ERROR), 0 if not
def compute_multi_lingual_consistency(all_dfs, model_name):

  col_names =  ['model', 'EN-DE', 'EN-DE Results', 'EN-FR', 'EN-FR Results', 'DE-FR', 'DE-FR Results']

  current_df = all_dfs[model_name]

  mlc_df  = pd.DataFrame(columns = col_names)

  offset_en_de = 40
  offset_en_fr = 80

  for i in range(40):

    en_row_status = current_df.loc[i, 'Status']
    de_row_status = current_df.loc[i + offset_en_de, 'Status']
    fr_row_status = current_df.loc[i + offset_en_fr, 'Status']

    mlc_df.loc[i, 'model'] = model_name
    mlc_df.loc[i, 'Query_Type'] = current_df.loc[i, 'Query_Type']
    mlc_df.loc[i, 'EN-DE'] = int(en_row_status == de_row_status)
    mlc_df.loc[i, 'EN-FR'] = int(en_row_status == fr_row_status)
    mlc_df.loc[i, 'DE-FR'] = int(de_row_status == fr_row_status)

    mlc_df.loc[i, 'EN-DE Results'] = en_row_status+"/"+de_row_status
    mlc_df.loc[i, 'EN-FR Results'] = en_row_status+"/"+fr_row_status
    mlc_df.loc[i, 'DE-FR Results'] = de_row_status+"/"+fr_row_status

  return mlc_df


mlc_df = compute_multi_lingual_consistency(all_dfs, MODEL_NAME)
mlc_df.describe()

,model,EN-DE,EN-DE Results,EN-FR,EN-FR Results,DE-FR,DE-FR Results,Query_Type
count,40,40,40,40,40,40,40,40
unique,1,2,4,2,4,2,4,9
top,gpt_5_4_mini,1,PASSED/PASSED,1,PASSED/PASSED,1,PASSED/PASSED,object/footprint
freq,40,35,28,25,19,24,18,10

In [ ]:
consistency_percentage = mlc_df.groupby('Query_Type')[['EN-DE', 'EN-FR', 'DE-FR']].mean() * 100

# Add a count column for each Query_Type
consistency_percentage['Count'] = mlc_df.groupby('Query_Type').size()

print("Percentage of Multilingual Consistency (1s) per Query_Type:")
display(consistency_percentage)

Percentage of Multilingual Consistency (1s) per Query_Type:

                              EN-DE      EN-FR      DE-FR  Count
Query_Type
cardinal (1:1)                100.0      100.0      100.0      3
cardinal (1:N)                100.0  66.666667  66.666667      3
distance (1:1)                100.0  66.666667  66.666667      3
distance (1:N)                100.0  66.666667  66.666667      3
object/footprint               90.0       70.0       60.0     10
physical/parts - comparison    80.0       20.0        0.0      5
physical/parts - enumeration   80.0       60.0       40.0      5
topological (1:1)              75.0       50.0       75.0      4
topological (1:N)              75.0       75.0      100.0      4

In [ ]:
consistency_percentage

                              EN-DE      EN-FR      DE-FR  Count
Query_Type
cardinal (1:1)                100.0      100.0      100.0      3
cardinal (1:N)                100.0  66.666667  66.666667      3
distance (1:1)                100.0  66.666667  66.666667      3
distance (1:N)                100.0  66.666667  66.666667      3
object/footprint               90.0       70.0       60.0     10
physical/parts - comparison    80.0       20.0        0.0      5
physical/parts - enumeration   80.0       60.0       40.0      5
topological (1:1)              75.0       50.0       75.0      4
topological (1:N)              75.0       75.0      100.0      4

## Putting everything together

In [ ]:
# Create a new DataFrame selecting the 'count' and 'mean' statistics specifically for the 'BERT_F1' metric
# The 'BERT_F1' column in the new DataFrame will represent the mean BERT_F1 score
new_stats_summary_df = pd.DataFrame({
    'count': desired_stats_nv_en[('BERT_F1', 'count')],
    'runtime (en)': desired_stats_nv_en[('Runtime (s)', 'mean')],
    'accuracy (en)': status_counts_en['Percentage_PASSED'],
    'judge_score (en)': desired_stats_nv_en[('Score', 'mean')],
    'BERT_F1 (en)': desired_stats_nv_en[('BERT_F1', 'mean')],

    'count': desired_stats_nv_de[('BERT_F1', 'count')],
    'runtime (de)': desired_stats_nv_de[('Runtime (s)', 'mean')],
    'accuracy (de)': status_counts_de['Percentage_PASSED'],
    'judge_score (de)': desired_stats_nv_de[('Score', 'mean')],
    'BERT_F1 (de)': desired_stats_nv_de[('BERT_F1', 'mean')],

    'count': desired_stats_nv_fr[('BERT_F1', 'count')],
    'runtime (fr)': desired_stats_nv_fr[('Runtime (s)', 'mean')],
    'accuracy (fr)': status_counts_fr['Percentage_PASSED'],
    'judge_score (fr)': desired_stats_nv_fr[('Score', 'mean')],
    'BERT_F1 (fr)': desired_stats_nv_fr[('BERT_F1', 'mean')],

    'MLC (EN-DE)': consistency_percentage['EN-DE'],
    'MLC (EN-FR)': consistency_percentage['EN-FR'],
    'MLC (DE-FR)': consistency_percentage['DE-FR']

})

new_stats_summary_df = new_stats_summary_df.reset_index()

print("New DataFrame with BERT_F1 Count and Mean (Query_Type as column):")
display(new_stats_summary_df)

New DataFrame with BERT_F1 Count and Mean (Query_Type as column):

,Query_Type,count,runtime (en),accuracy (en),judge_score (en),BERT_F1 (en),runtime (de),accuracy (de),judge_score (de),BERT_F1 (de),runtime (fr),accuracy (fr),judge_score (fr),BERT_F1 (fr),MLC (EN-DE),MLC (EN-FR),MLC (DE-FR)
0,cardinal (1:1),3.0,5.301667,100.000000,1.000000,0.529200,5.527000,100.000000,1.000000,0.459767,5.119000,100.000000,1.000000,0.549033,100.0,100.0,100.0
1,cardinal (1:N),3.0,31.089333,100.000000,1.000000,0.506267,32.172333,100.000000,1.000000,0.535000,31.372333,66.666667,0.933333,0.466633,100.0,66.666667,66.666667
2,distance (1:1),3.0,10.529000,100.000000,1.000000,0.519167,12.808667,100.000000,1.000000,0.450800,8.814667,66.666667,0.666667,0.240433,100.0,66.666667,66.666667
3,distance (1:N),3.0,42.679333,66.666667,0.906667,0.663367,39.274333,66.666667,0.876667,0.573667,39.999667,100.000000,0.916667,0.615767,100.0,66.666667,66.666667
4,object/footprint,10.0,4.847900,60.000000,0.660000,0.490210,4.444100,70.000000,0.770000,0.577110,4.148200,30.000000,0.360000,0.147530,90.0,70.0,60.0
5,physical/parts - comparison,5.0,4.361400,40.000000,0.400000,0.553580,4.116600,60.000000,0.600000,0.393280,4.103400,40.000000,0.400000,0.349300,80.0,20.0,0.0
6,physical/parts - enumeration,5.0,4.295400,100.000000,1.000000,0.697480,4.656400,80.000000,0.800000,0.500400,4.544800,60.000000,0.764000,0.447620,80.0,60.0,40.0
7,topological (1:1),4.0,5.041000,75.000000,0.725000,0.253800,4.542000,50.000000,0.500000,0.299225,4.991750,25.000000,0.325000,0.289675,75.0,50.0,75.0
8,topological (1:N),4.0,4.012250,100.000000,1.000000,0.645075,4.674250,75.000000,0.750000,0.547125,4.002250,75.000000,0.750000,0.484000,75.0,75.0,100.0

In [ ]:
new_stats_summary_df.keys()

Index(['Query_Type', 'count', 'runtime (en)', 'accuracy (en)',
       'judge_score (en)', 'BERT_F1 (en)', 'runtime (de)', 'accuracy (de)',
       'judge_score (de)', 'BERT_F1 (de)', 'runtime (fr)', 'accuracy (fr)',
       'judge_score (fr)', 'BERT_F1 (fr)', 'MLC (EN-DE)', 'MLC (EN-FR)',
       'MLC (DE-FR)'],
      dtype='object')

In [ ]:
output_excel_filename = 'model_summary_statistics_'+model_name+'.xlsx'
new_stats_summary_df.to_excel(output_excel_filename, index=False)

print(f"DataFrame exported to {output_excel_filename} for the model {model_name}")

DataFrame exported to model_summary_statistics_gpt_5_4_mini.xlsx for the model gpt_5_4_mini